# Generated by Django 5.1 on 2024-10-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('date_debut', models.DateTimeField(null=True)),
                ('date_fin', models.DateTimeField(null=True)),
                ('prix', models.FloatField(default=0, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft '), (1, 'Publié ')], default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MupendaApp.category')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
