# Generated by Django 5.1 on 2024-10-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0002_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropos',
            options={'ordering': ['date_ajout']},
        ),
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MupendaApp.category'),
        ),
    ]
