# Generated by Django 5.1 on 2024-11-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['date_ajout']},
        ),
        migrations.AddField(
            model_name='apropos',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apropos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realisation',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realisation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MupendaApp.category'),
        ),
        migrations.AddField(
            model_name='temoignageclient',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temoignage_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
