# Generated by Django 5.1 on 2024-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0005_alter_services_options_apropos_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
