# Generated by Django 5.1 on 2024-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0006_alter_formation_date_debut_alter_formation_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
