# Generated by Django 5.1 on 2024-11-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0007_realisation_slug_services_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
