# Generated by Django 5.1 on 2024-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0008_alter_formation_options_formation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
