# Generated by Django 5.1 on 2024-11-11 11:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0009_formation_heure_debut_formation_heure_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
