# Generated by Django 5.1 on 2024-11-11 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0010_alter_formation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apropos',
            name='contenus',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='temoignageclient',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
