# Generated by Django 5.1.7 on 2025-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0012_apropos_update_on_category_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='autres_details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
