# Generated by Django 5.1.7 on 2025-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0013_equipement_autres_details_equipement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('addresse', models.CharField(default='Goma/Nord-Kivu', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('specialite', models.CharField(default='Formateur', max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
