# Generated by Django 6.0.1 on 2026-01-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0014_formateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apropos',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
