# Generated by Django 6.0.1 on 2026-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0015_remove_apropos_status_customuser_photo_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
