# Generated by Django 6.0.1 on 2026-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0016_alter_services_options_alter_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apropos',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temoignageclient',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
