# Generated by Django 6.0.1 on 2026-01-29 10:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0017_alter_apropos_update_on_alter_category_update_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('type_client', models.CharField(choices=[('PME', 'PME'), ('STARTUP', 'Startup'), ('GRAND_COMPTE', 'Grand Compte'), ('PARTICULIER', 'Particulier')], default='PARTICULIER', max_length=20)),
                ('statut_client', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé')], default='PROSPECT', max_length=20)),
                ('siret', models.CharField(blank=True, help_text='Numéro SIRET pour les entreprises', max_length=14, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('responsable_compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('EMAIL', 'Email'), ('RENDEZ_VOUS', 'Rendez-vous'), ('REUNION', 'Réunion'), ('DEMONSTRATION', 'Démonstration'), ('PROPOSITION', 'Proposition commerciale'), ('SUIVI', 'Suivi'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_interaction', models.DateTimeField()),
                ('duree_minutes', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('sujet', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('prochain_rappel', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='MupendaApp.client')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_realisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'interaction",
                'verbose_name_plural': 'Historique des interactions',
                'ordering': ['-date_interaction'],
            },
        ),
        migrations.CreateModel(
            name='AssociationClientProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_dans_projet', models.CharField(default='Client', max_length=100)),
                ('budget_alloue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut_association', models.DateField()),
                ('date_fin_association', models.DateField(blank=True, null=True)),
                ('statut_association', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('notes_association', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_client', to='MupendaApp.realisation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_projet', to='MupendaApp.client')),
            ],
            options={
                'verbose_name': 'Association Client-Projet',
                'verbose_name_plural': 'Associations Clients-Projets',
                'ordering': ['-date_debut_association'],
                'unique_together': {('client', 'projet')},
            },
        ),
    ]
