# Generated by Django 6.0.1 on 2026-01-29 13:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0018_client_historiqueinteraction_associationclientprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFICATION', 'Planification'), ('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFICATION', max_length=20)),
                ('type_projet', models.CharField(choices=[('FORFAIT', 'Forfait'), ('REGIE', 'Régie'), ('MAINTENANCE', 'Maintenance'), ('CONSULTING', 'Consulting')], default='FORFAIT', max_length=20)),
                ('budget_initial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_consomme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=10)),
                ('progression', models.IntegerField(default=0, help_text='Progression en pourcentage')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='MupendaApp.client')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SuiviTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateField()),
                ('heures', models.DecimalField(decimal_places=2, help_text="Nombre d'heures travaillées", max_digits=5)),
                ('description', models.TextField(help_text='Description du travail effectué')),
                ('type_travail', models.CharField(choices=[('DEVELOPPEMENT', 'Développement'), ('ANALYSE', 'Analyse'), ('TEST', 'Test'), ('REUNION', 'Réunion'), ('DOCUMENTATION', 'Documentation'), ('MAINTENANCE', 'Maintenance'), ('AUTRE', 'Autre')], default='DEVELOPPEMENT', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_saisi', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_temps', to='MupendaApp.projet')),
            ],
            options={
                'verbose_name': 'Suivi du temps',
                'verbose_name_plural': 'Suivis du temps',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='AffectationCollaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHEF_PROJET', 'Chef de projet'), ('DEVELOPPEUR', 'Développeur'), ('DESIGNER', 'Designer'), ('TESTEUR', 'Testeur'), ('CONSULTANT', 'Consultant'), ('ANALYSTE', 'Analyste'), ('AUTRE', 'Autre')], default='DEVELOPPEUR', max_length=20)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('date_fin_affectation', models.DateField(blank=True, null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_projet', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='MupendaApp.projet')),
            ],
            options={
                'verbose_name': 'Affectation collaborateur',
                'verbose_name_plural': 'Affectations collaborateurs',
                'ordering': ['-date_affectation'],
                'unique_together': {('projet', 'collaborateur')},
            },
        ),
    ]
