# Generated by Django 6.0.1 on 2026-01-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0019_projet_suivitemps_affectationcollaborateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivitemps',
            name='commentaire_validation',
            field=models.TextField(blank=True, help_text='Commentaire du validateur', null=True),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant calculé automatiquement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux horaire pour calcul du montant', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_temps', to=settings.AUTH_USER_MODEL),
        ),
    ]
