# Generated by Django 5.2.10 on 2026-01-31 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0021_collaborateur_devis_facture_lignefacture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('UTILISATEUR', 'Gestion des utilisateurs'), ('ROLE', 'Gestion des rôles'), ('PROJET', 'Gestion des projets'), ('CLIENT', 'Gestion des clients'), ('FACTURATION', 'Gestion de la facturation'), ('CONTENU', 'Gestion du contenu'), ('RAPPORT', 'Accès aux rapports'), ('SYSTEME', 'Administration système'), ('SUPPORT', 'Gestion du support'), ('FORMATION', 'Gestion des formations')], max_length=20)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='messageticket',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='messageticket',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='assigne_a',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='projet_concerne',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='resolu_par',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bloque_jusqua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tentative_echec',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMINISTRATEUR', 'Administrateur'), ('CHEF_PROJET', 'Chef de Projet'), ('DEVELOPPEUR', 'Développeur'), ('DESIGNER', 'Designer'), ('COMMERCIAL', 'Commercial'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('SUPPORT', 'Support Technique'), ('CLIENT', 'Client'), ('COLLABORATEUR', 'Collaborateur'), ('FORMATEUR', 'Formateur'), ('STAGIAIRE', 'Stagiaire')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_hierarchique', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='MupendaApp.permission')),
            ],
            options={
                'ordering': ['-niveau_hierarchique', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='MupendaApp.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_attribution'],
                'unique_together': {('utilisateur', 'role')},
            },
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='LigneFacture',
        ),
        migrations.DeleteModel(
            name='MessageTicket',
        ),
        migrations.DeleteModel(
            name='TicketSupport',
        ),
    ]
