# Generated by Django 5.2.10 on 2026-02-01 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0022_permission_remove_devis_client_remove_devis_cree_par_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu_usage', 'Utilisation CPU'), ('memory_usage', 'Utilisation Mémoire'), ('disk_usage', 'Utilisation Disque'), ('network_traffic', 'Trafic Réseau'), ('database_connections', 'Connexions BD'), ('cache_hit_rate', 'Taux Cache Hit'), ('response_time', 'Temps de Réponse')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='%', max_length=20)),
                ('threshold_warning', models.FloatField(default=80.0)),
                ('threshold_critical', models.FloatField(default=90.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='MupendaApp__metric__a3a755_idx'), models.Index(fields=['timestamp'], name='MupendaApp__timesta_2dd686_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('backup', 'Sauvegarde'), ('restore', 'Restauration')], max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='MupendaApp__user_id_c157b5_idx'), models.Index(fields=['action', 'timestamp'], name='MupendaApp__action_e958bb_idx'), models.Index(fields=['model_name', 'timestamp'], name='MupendaApp__model_n_40ccdd_idx'), models.Index(fields=['timestamp'], name='MupendaApp__timesta_aebee1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Complète'), ('incremental', 'Incrémentale'), ('differential', 'Différentielle')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('compression_ratio', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backup_type', 'status'], name='MupendaApp__backup__8a0460_idx'), models.Index(fields=['status', 'created_at'], name='MupendaApp__status_d97193_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('failed_login', 'Connexion échouée'), ('suspicious_activity', 'Activité suspecte'), ('blocked_ip', 'IP bloquée'), ('malware_detected', 'Malware détecté'), ('vulnerability', 'Vulnérabilité'), ('data_breach', 'Fuite de données')], max_length=50)),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='MupendaApp__metric__5aeb20_idx'), models.Index(fields=['severity', 'resolved'], name='MupendaApp__severit_3a295d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('unknown', 'Inconnu')], default='unknown', max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Inactif'), ('suspicious', 'Suspect'), ('blocked', 'Bloqué'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='MupendaApp__user_id_d88788_idx'), models.Index(fields=['ip_address', 'status'], name='MupendaApp__ip_addr_eac39e_idx'), models.Index(fields=['status', 'last_activity'], name='MupendaApp__status_657990_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('security', 'Sécurité'), ('performance', 'Performance'), ('storage', 'Stockage'), ('backup', 'Sauvegarde'), ('maintenance', 'Maintenance'), ('error', 'Erreur'), ('warning', 'Avertissement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'is_active'], name='MupendaApp__alert_t_29b742_idx'), models.Index(fields=['severity', 'is_read'], name='MupendaApp__severit_f93919_idx'), models.Index(fields=['is_active', 'created_at'], name='MupendaApp__is_acti_8c0bf9_idx')],
            },
        ),
    ]
