# Generated by Django 5.2.10 on 2026-02-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0023_systemmetric_adminauditlog_backuplog_securitymetric_and_more'),
    ]

    operations = [
    ]
