# Generated by Django 5.2.10 on 2026-02-01 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0024_auto_20260201_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(default='#FF6700', max_length=7)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('VISUALISATION', 'Visualisation'), ('EXPORTATION', 'Exportation'), ('AUTRE', 'Autre')], max_length=20)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('id_objet', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'action",
                'verbose_name_plural': "Logs d'actions",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('AVERTISSEMENT', 'Avertissement'), ('ERREUR', 'Erreur'), ('TACHE', 'Tâche'), ('PROJET', 'Projet'), ('SYSTEME', 'Système')], default='INFO', max_length=20)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=500, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_REVISION', 'En révision'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='A_FAIRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_terminee', models.DateTimeField(blank=True, null=True)),
                ('temps_estime', models.IntegerField(blank=True, help_text='Temps estimé en heures', null=True)),
                ('temps_passe', models.IntegerField(default=0, help_text='Temps passé en heures')),
                ('progression', models.IntegerField(default=0, help_text='Pourcentage de progression (0-100)')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backuplog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='securitymetric',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemalert',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='SystemMetric',
        ),
        migrations.AlterModelOptions(
            name='associationclientprojet',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='budget_consomme',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='cree_le',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='modifie_le',
            new_name='date_modification',
        ),
        migrations.AlterUniqueTogether(
            name='associationclientprojet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='budget_initial',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='type_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin_prevue',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.ManyToManyField(blank=True, related_name='projets_equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_chef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=10),
        ),
        migrations.AlterField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(default=0, help_text='Pourcentage de progression (0-100)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('PLANIFICATION', 'Planification'), ('EN_COURS', 'En cours'), ('EN_PAUSE', 'En pause'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFICATION', max_length=20),
        ),
        migrations.AddField(
            model_name='projet',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='MupendaApp.departement'),
        ),
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='MupendaApp.projet'),
        ),
        migrations.DeleteModel(
            name='AdminAuditLog',
        ),
        migrations.DeleteModel(
            name='BackupLog',
        ),
        migrations.DeleteModel(
            name='SecurityMetric',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
        migrations.DeleteModel(
            name='SystemAlert',
        ),
    ]
