# Generated by Django 5.2.10 on 2026-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0025_departement_logaction_notification_tache_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationclientprojet',
            options={'ordering': ['-date_debut_association'], 'verbose_name': 'Association Client-Projet', 'verbose_name_plural': 'Associations Clients-Projets'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='pref_dark_mode',
            field=models.BooleanField(default=False, verbose_name='Mode sombre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pref_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications par email'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='categorie',
            field=models.CharField(choices=[('UTILISATEUR', 'Gestion des utilisateurs'), ('ROLE', 'Gestion des rôles'), ('DEPARTEMENT', 'Gestion des départements'), ('PROJET', 'Gestion des projets'), ('TACHE', 'Gestion des tâches'), ('CLIENT', 'Gestion des clients'), ('FACTURATION', 'Gestion de la facturation'), ('CONTENU', 'Gestion du contenu'), ('RAPPORT', 'Accès aux rapports'), ('SYSTEME', 'Administration système'), ('SUPPORT', 'Gestion du support'), ('FORMATION', 'Gestion des formations')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='associationclientprojet',
            unique_together={('client', 'projet')},
        ),
    ]
