# Generated by Django 5.2.10 on 2026-02-28 21:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0027_partenaire_post_category_alter_services_slug_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLegale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_page', models.CharField(choices=[('CGU', "Conditions Générales d'Utilisation"), ('POLITIQUE', 'Politique de Confidentialité'), ('MENTIONS', 'Mentions Légales')], max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=500, null=True)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field()),
                ('derniere_mise_a_jour', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Légale',
                'verbose_name_plural': 'Pages Légales',
                'ordering': ['type_page'],
            },
        ),
    ]
