# Generated by Django 5.2.10 on 2026-03-03 09:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0028_pagelegale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_desinscription', models.DateTimeField(blank=True, null=True)),
                ('ip_inscription', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('nombre_destinataires', models.IntegerField(default=0)),
                ('nombre_ouverts', models.IntegerField(default=0)),
                ('est_brouillon', models.BooleanField(default=False)),
                ('envoye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne Newsletter',
                'verbose_name_plural': 'Campagnes Newsletter',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
