# Generated by Django 6.0.1 on 2026-03-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0029_newslettersubscriber_newslettercampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('type_projet', models.CharField(choices=[('SITE_WEB', 'Site Web'), ('APPLICATION', 'Application Mobile/Desktop'), ('LOGICIEL', 'Logiciel sur mesure'), ('RESEAU', 'Infrastructure Réseau'), ('SECURITE', 'Cyber Sécurité'), ('MARKETING', 'Marketing Digital'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField(help_text='Description détaillée du projet')),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_COURS', 'En cours de traitement'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text="Montant proposé par l'admin", max_digits=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('reponse_admin', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
