# Generated by Django 5.2.10 on 2026-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0030_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='type_projet',
            field=models.CharField(choices=[('DEVIS_GENERAL', 'Demande de devis générale'), ('SITE_WEB', 'Site Web'), ('APPLICATION', 'Application Mobile/Desktop'), ('LOGICIEL', 'Logiciel sur mesure'), ('RESEAU', 'Infrastructure Réseau'), ('SECURITE', 'Cyber Sécurité'), ('MARKETING', 'Marketing Digital'), ('FORMATION', 'Formation'), ('CONSULTING', 'Consulting IT'), ('MAINTENANCE', 'Maintenance/Support'), ('AUTRE', 'Autre')], default='AUTRE', max_length=25),
        ),
    ]
