# Generated by Django 5.2.10 on 2026-03-05 14:48

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0031_alter_devis_type_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropos',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Page À propos', 'verbose_name_plural': 'Page À propos'},
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='contenus',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='update_on',
        ),
        migrations.AddField(
            model_name='apropos',
            name='annee_experience',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='apropos',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='description_entreprise',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='icon_mission',
            field=models.CharField(default='bi-rocket-takeoff-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='icon_objectifs',
            field=models.CharField(default='bi-bullseye', max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='icon_valeurs',
            field=models.CharField(default='bi-heart-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='label_annee_experience',
            field=models.CharField(default="Années d'expérience", max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='label_clients',
            field=models.CharField(default='Clients satisfaits', max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='label_projets',
            field=models.CharField(default='Projets réalisés', max_length=50),
        ),
        migrations.AddField(
            model_name='apropos',
            name='mission_1',
            field=models.CharField(default='Apporter une assistance technologique et informatique aux entreprises congolaises', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='mission_2',
            field=models.CharField(default="Encadrer et former les jeunes ambitieux dotés d'un esprit d'innovation", max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='mission_3',
            field=models.CharField(default="Contribuer à la digitalisation de l'Afrique", max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='mission_4',
            field=models.CharField(default='Offrir des solutions technologiques accessibles à tous', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='nom_entreprise',
            field=models.CharField(default='Mupenda Company', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='nombre_clients',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='apropos',
            name='nombre_projets',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='apropos',
            name='objectif_1',
            field=models.CharField(default='Créer une stratégie marketing basée sur les objectifs et les cibles du client', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='objectif_2',
            field=models.CharField(default='Créer et offrir des emplois partout en RDC et en Afrique', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='objectif_3',
            field=models.CharField(default="Etre une société au cœur de l'innovation congolaise et africaine", max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='objectif_4',
            field=models.CharField(default='Promouvoir la technologie congolaise et africaine', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='photo_principale',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/apropos'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='sous_titre_page',
            field=models.TextField(default='Découvrez Mupenda Company, votre partenaire technologique de confiance en RDC et en Afrique.'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='titre_mission',
            field=models.CharField(default='Notre Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='apropos',
            name='titre_objectifs',
            field=models.CharField(default='Nos Objectifs', max_length=100),
        ),
        migrations.AddField(
            model_name='apropos',
            name='titre_page',
            field=models.CharField(default='Qui sommes-nous ?', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='titre_section_valeurs',
            field=models.CharField(default='Nos Valeurs & Objectifs', max_length=100),
        ),
        migrations.AddField(
            model_name='apropos',
            name='titre_valeurs',
            field=models.CharField(default='Nos Valeurs', max_length=100),
        ),
        migrations.AddField(
            model_name='apropos',
            name='valeur_1',
            field=models.CharField(default='Respect de la vie privée et dignité de nos clients', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='valeur_2',
            field=models.CharField(default='Motivation et engagement dans chaque projet', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='valeur_3',
            field=models.CharField(default='Créativité et innovation continue', max_length=255),
        ),
        migrations.AddField(
            model_name='apropos',
            name='valeur_4',
            field=models.CharField(default='Excellence et qualité dans nos livrables', max_length=255),
        ),
        migrations.AlterField(
            model_name='apropos',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apropos_modifies', to=settings.AUTH_USER_MODEL),
        ),
    ]
