# Generated by Django 5.2.10 on 2026-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MupendaApp', '0032_alter_apropos_options_remove_apropos_contenus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_complete', models.TextField(default='Goma, République Démocratique du Congo', help_text="Adresse complète de l'entreprise")),
                ('telephone_principal', models.CharField(default='(+243) 000 000 000', help_text='Numéro de téléphone principal', max_length=50)),
                ('telephone_secondaire', models.CharField(blank=True, help_text='Numéro de téléphone secondaire (optionnel)', max_length=50, null=True)),
                ('email_principal', models.EmailField(default='contact@mupenda.cd', help_text='Email principal de contact', max_length=100)),
                ('email_support', models.EmailField(blank=True, help_text='Email pour le support client', max_length=100, null=True)),
                ('horaires_ouverture', models.CharField(default='Lundi - Samedi : 08h00 - 16h00', help_text="Horaires d'ouverture (texte libre)", max_length=255)),
                ('facebook_url', models.URLField(blank=True, help_text='URL de la page Facebook', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='URL de la page Twitter/X', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='URL de la page LinkedIn', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='URL de la page Instagram', null=True)),
                ('carte_embed_url', models.URLField(blank=True, help_text='URL embed Google Maps (iframe)', null=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Si coché, ces informations seront affichées sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de Contact',
                'verbose_name_plural': 'Informations de Contact',
            },
        ),
    ]
